[rtmp]
enabled = true
port = 1935

# pull streams from other server node.
[rtmp.pull]
enabled = false
address = "192.168.0.1"
port = 1935

# push streams to other server node.
[[rtmp.push]]
enabled = true
address = "localhost"
port = 1936
#[[rtmp.push]]
#enabled = true
#address = "192.168.0.3"
#port = 1935

[httpflv]
# true or false to enable or disable the feature
enabled = true
# listening port
port = 8081

[hls]
# true or false to enable or disable the feature
enabled = true
# listening port
port = 8080

[log]
level = "info"

